# SSD300 Inference Tutorial

This is a brief tutorial that shows how to use a trained SSD300 for inference on the Pascal VOC datasets. If you'd like more detailed explanations, please refer to [`ssd300_training.ipynb`](https://github.com/pierluigiferrari/ssd_keras/blob/master/ssd300_training.ipynb)

In [2]:
from keras import backend as K
from keras.models import load_model
from keras.preprocessing import image
from keras.optimizers import Adam
from imageio import imread
import numpy as np
from matplotlib import pyplot as plt

from models.keras_ssd300_mod_all import ssd_300
from keras_loss_function.keras_ssd_loss_mod import SSDLoss
from keras_loss_function.keras_ssd_loss_proj import SSDLoss_proj

from keras_layers.keras_layer_AnchorBoxes import AnchorBoxes
from keras_layers.keras_layer_DecodeDetections import DecodeDetections
from keras_layers.keras_layer_DecodeDetectionsFast import DecodeDetectionsFast
from keras_layers.keras_layer_L2Normalization import L2Normalization

from ssd_encoder_decoder.ssd_output_decoder import decode_detections, decode_detections_fast

from data_generator.object_detection_2d_data_generator import DataGenerator
from data_generator.object_detection_2d_geometric_ops import Resize_Modified
from data_generator.object_detection_2d_photometric_ops import ConvertTo3Channels_Modified
from data_generator.data_augmentation_chain_original_ssd import SSDDataAugmentation_modified
from data_generator.object_detection_2d_misc_utils import apply_inverse_transforms

%matplotlib inline

In [3]:
# Set the image size.
img_height = 300
img_width = 600

## 1. Load a trained SSD

Either load a trained model or build a model and load trained weights into it. Since the HDF5 files I'm providing contain only the weights for the various SSD versions, not the complete models, you'll have to go with the latter option when using this implementation for the first time. You can then of course save the model and next time load the full model directly, without having to build it.

You can find the download links to all the trained model weights in the README.

### 1.1. Build the model and load trained weights into it

In [6]:
# 1: Build the Keras model

K.clear_session() # Clear precheckpoints/checkpoints/EXP3/double_ssd300_8.h5vious models from memory.

model = ssd_300(image_size=(img_height, img_width, 3),
                n_classes=1,
                mode='inference',
                l2_regularization=0.0005,
                scales=[0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05], # The scales for MS COCO are [0.07, 0.15, 0.33, 0.51, 0.69, 0.87, 1.05]
                aspect_ratios_per_layer=[[1.0, 2.0, 0.5],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5, 3.0, 1.0/3.0],
                                         [1.0, 2.0, 0.5],
                                         [1.0, 2.0, 0.5]],
                two_boxes_for_ar1=True,
                steps=[8, 16, 32, 64, 100, 300],
                offsets=[0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
                clip_boxes=False,
                variances=[0.1, 0.1, 0.2, 0.2],
                normalize_coords=True,
                subtract_mean=[123, 117, 104],
                swap_channels=[2, 1, 0],
                confidence_thresh=0.5,
                iou_threshold=0.45,
                top_k=200,
                nms_max_output_size=400)

# 2: Load the trained weights into the model.

# TODO: Set the path of the trained weights.
weights_path = 'checkpoints/double_ssd300_pascal_07+12_epoch-20_loss-15.4517_val_loss-14.4820.h5'

model.load_weights(weights_path, by_name=True)

# 3: Compile the model so that Keras won't complain the next time you load it.

adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)

# ssd_loss1 = SSDLoss(neg_pos_ratio=3, alpha=1.0)
# ssd_loss2 = SSDLoss(neg_pos_ratio=3, alpha=1.0)
# ssd_loss3 = SSDLoss_proj(neg_pos_ratio=3, alpha=1.0)
# ssd_loss4 = SSDLoss_proj(neg_pos_ratio=3, alpha=1.0)

# losses = {
#     "predictions_1": ssd_loss1.compute_loss,
#     "predictions_2": ssd_loss2.compute_loss,
#     "predictions_1_proj": ssd_loss3.compute_loss,
#     "predictions_2_proj": ssd_loss4.compute_loss

# }
ssd_loss = SSDLoss(neg_pos_ratio=3, alpha=1.0)

model.compile(optimizer=adam, loss=ssd_loss.compute_loss)

/home/nassar/gits/ssd_keras_double/models/keras_ssd300_mod_all.py:579: UserWarning: Update your `Model` call to the Keras 2 API: `Model(outputs=[<tf.Tenso..., inputs=[<tf.Tenso...)`
  model = Model(input=[x,geo_1,geo_2],output=[mbox_conf, mbox_loc, mbox_priorbox])


In [ ]:
model.summary()

## 2. Load some images

Load some images for which you'd like the model to make predictions.

In [7]:
orig_images = [] # Store the images here.
input_images = [] # Store resized versions of the images here.

# We'll only load one image in this example.
img_path = '../datasets/Images/7tdpKEm0YIlJVJ8AK7zkdw_z2.jpg'

orig_images.append(imread(img_path))
img = image.load_img(img_path, target_size=(img_height, img_width))
img = image.img_to_array(img) 
input_images.append(img)
input_images = np.array(input_images)

In [11]:
orig_images1 = [] # Store the images here.
input_images1 = [] # Store resized versions of the images here.

# We'll only load one image in this example.
img_path1 = '../datasets/Images/ZrJFziHS3ADOec3trJb8hA_z2.jpg'

orig_images1.append(imread(img_path1))
img1 = image.load_img(img_path1, target_size=(img_height, img_width))
img1 = image.img_to_array(img1) 
input_images1.append(img1)
input_images1 = np.array(input_images1)

## 3. Make predictions

In [8]:
geox = np.tile(np.array([34.156992,-118.165118,0.9073966781118519],dtype=np.float64), (17292,1))
geoz = np.tile(np.array([34.156939,-118.165203,0.9061749476354559],dtype=np.float64), (17292,1))

geox = np.array([34.1513108639,-118.135291797,20],dtype=np.float64)
geoz = np.array([34.1513108639,-118.135291797,21],dtype=np.float64)

In [9]:
geox = np.expand_dims(geox, axis=0)
geoz = np.expand_dims(geoz, axis=0)

In [12]:
y_pred = model.predict([input_images,input_images1,geox,geoz])

`y_pred` contains a fixed number of predictions per batch item (200 if you use the original model configuration), many of which are low-confidence predictions or dummy entries. We therefore need to apply a confidence threshold to filter out the bad predictions. Set this confidence threshold value how you see fit.

In [14]:
sia = model.predict([input_images,input_images1,geox,geoz])

(1, 200, 24)

In [13]:
y_pred_1 = y_pred[:,:,:6]
y_pred_1_on_2 = y_pred[:,:,6:12]
y_pred_2 = y_pred[:,:,12:18]
y_pred_2_on_1 = y_pred[:,:,18:]


In [14]:
confidence_threshold = 0.5

y_pred_thresh_1 = [y_pred_1[k][y_pred_1[k,:,1] > confidence_threshold] for k in range(y_pred_1.shape[0])]
y_pred_thresh_2 = [y_pred_2[k][y_pred_2[k,:,1] > confidence_threshold] for k in range(y_pred_2.shape[0])]
y_pred_thresh_1_p = [y_pred_1_on_2[k][y_pred_1_on_2[k,:,1] > confidence_threshold] for k in range(y_pred_1_on_2.shape[0])]
y_pred_thresh_2_p = [y_pred_2_on_1[k][y_pred_2_on_1[k,:,1] > confidence_threshold] for k in range(y_pred_2_on_1.shape[0])]

np.set_printoptions(precision=2, suppress=True, linewidth=90)
print("Predicted boxes 1:\n")
print('   class   conf xmin   ymin   xmax   ymax')
print(y_pred_thresh_1[0])
print("Predicted boxes 2n")
print('   class   conf xmin   ymin   xmax   ymax')
print(y_pred_thresh_2[0])
print("Predicted boxes 1 proj")
print('   class   conf xmin   ymin   xmax   ymax')
print(y_pred_thresh_1_p[0])
print("Predicted boxes 2 proj")
print('   class   conf xmin   ymin   xmax   ymax')
print(y_pred_thresh_2_p[0])


Predicted boxes 1:

   class   conf xmin   ymin   xmax   ymax
[[  1.     0.93 193.93  70.34 282.49 166.88]
 [  1.     0.91   5.22  44.23 131.57 168.61]
 [  1.     0.88 306.27  89.75 357.05 159.22]
 [  1.     0.86 455.02  54.31 552.03 165.84]
 [  1.     0.76 370.48  93.3  413.79 166.49]
 [  1.     0.68 130.17  87.03 186.76 162.76]
 [  1.     0.6  250.61 117.73 285.26 162.72]]
Predicted boxes 2n
   class   conf xmin   ymin   xmax   ymax
[[  1.     0.94 409.25  51.1  521.39 168.15]
 [  1.     0.91 243.33 107.17 295.4  160.22]
 [  1.     0.72 162.97  94.47 224.81 159.96]
 [  1.     0.68  18.14  26.39 188.01 174.34]]
Predicted boxes 1 proj
   class   conf xmin   ymin   xmax   ymax
[[  1.     0.93 207.2   79.2  288.8  160.8 ]
 [  1.     0.91  12.95  44.95 147.05 179.05]
 [  1.     0.88 306.79  77.57 349.21 162.43]
 [  1.     0.86 440.5   56.5  551.5  167.5 ]
 [  1.     0.76 370.79  93.57 413.21 178.43]
 [  1.     0.71 314.    90.   374.   150.  ]
 [  1.     0.69 366.79 110.79 409.21 153.21]


## 4. Visualize the predictions

We just resized the input image above and made predictions on the distorted image. We'd like to visualize the predictions on the image in its original size though, so below we'll transform the coordinates of the predicted boxes accordingly.

In [ ]:
dataset = DataGenerator()

# TODO: Set the paths to the datasets here.

VOC_2007_images_dir      = '../datasets/Images/'
VOC_2007_annotations_dir      = '../datasets/VOC/Pasadena/Annotations_Multi/'
VOC_2007_test_image_set_filename     = '../datasets/VOC/Pasadena/ImageSets/Main/reid_neu/test_one.txt'

# The XML parser needs to now what object class names to look for and in which order to map them to integers.
classes = ['background',
           'tree']

dataset.parse_xml(images_dirs=[VOC_2007_images_dir],
                  image_set_filenames=[VOC_2007_test_image_set_filename],
                  annotations_dirs=[VOC_2007_annotations_dir],
                  classes=classes,
                  include_classes='all',
                  exclude_truncated=False,
                  exclude_difficult=False,
                  ret=False)

convert_to_3_channels = ConvertTo3Channels_Modified()  
resize = Resize_Modified(height=img_height, width=img_width)

generator = dataset.generate_inf_gt(batch_size=1,
                             shuffle=True,
                             transformations=[convert_to_3_channels,
                                              resize],
                             returns={'processed_images',
                                      'filenames',
                                      'inverse_transform',
                                      'original_images',
                                      'original_labels'},
                             keep_images_without_gt=False)


In [ ]:
batch_images,batch_images1, batch_filenames, batch_inverse_transforms,batch_inverse_transforms1, batch_original_images,batch_original_images1, batch_original_labels,batch_original_labels1 = next(generator)

i = 0 # Which batch item to look at

print("Image:", batch_filenames[i][0])
print()
print("Ground truth boxes:\n")
print(np.array(batch_original_labels[i]))


In [ ]:
# Set the colors for the bounding boxes
colors = plt.cm.hsv(np.linspace(0, 1, 21)).tolist()

plt.figure(figsize=(20,12))
plt.imshow(batch_original_images[i])

current_axis = plt.gca()

for box in batch_original_labels[i]:
    xmin = box[1]
    ymin = box[2]
    xmax = box[3]
    ymax = box[4]
    label = '{}'.format(classes[int(box[0])])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color='green', fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':'green', 'alpha':1.0})

for box in y_pred_thresh_1[i]:
    xmin = box[2] * orig_images[0].shape[1] / img_width
    ymin = box[3] * orig_images[0].shape[0] / img_height
    xmax = box[4] * orig_images[0].shape[1] / img_width
    ymax = box[5] * orig_images[0].shape[0] / img_height
    color = colors[int(box[0])]
    label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color=color, fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':color, 'alpha':1.0})


In [ ]:
plt.figure(figsize=(20,12))
plt.imshow(batch_original_images1[i])

current_axis = plt.gca()

for box in batch_original_labels1[i]:
    xmin = box[1]
    ymin = box[2]
    xmax = box[3]
    ymax = box[4]
    label = '{}'.format(classes[int(box[0])])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color='green', fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':'green', 'alpha':1.0})

for box in y_pred_thresh_2[i]:
    xmin = box[2] * orig_images[0].shape[1] / img_width
    ymin = box[3] * orig_images[0].shape[0] / img_height
    xmax = box[4] * orig_images[0].shape[1] / img_width
    ymax = box[5] * orig_images[0].shape[0] / img_height
    color = colors[int(box[0])]
    label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color=color, fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':color, 'alpha':1.0})


In [ ]:
plt.figure(figsize=(20,12))
plt.imshow(batch_original_images[i])

current_axis = plt.gca()

for box in batch_original_labels[i]:
    xmin = box[1]
    ymin = box[2]
    xmax = box[3]
    ymax = box[4]
    label = '{}'.format(classes[int(box[0])])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color='green', fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':'green', 'alpha':1.0})

for box in y_pred_thresh_2_p[i]:
    xmin = box[2] * orig_images[0].shape[1] / img_width
    ymin = box[3] * orig_images[0].shape[0] / img_height
    xmax = box[4] * orig_images[0].shape[1] / img_width
    ymax = box[5] * orig_images[0].shape[0] / img_height
    color = colors[int(box[0])]
    label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color=color, fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':color, 'alpha':1.0})


In [ ]:
plt.figure(figsize=(20,12))
plt.imshow(batch_original_images1[i])

current_axis = plt.gca()

for box in batch_original_labels1[i]:
    xmin = box[1]
    ymin = box[2]
    xmax = box[3]
    ymax = box[4]
    label = '{}'.format(classes[int(box[0])])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color='green', fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':'green', 'alpha':1.0})

for box in y_pred_thresh_1_p[i]:
    xmin = box[2] * orig_images[0].shape[1] / img_width
    ymin = box[3] * orig_images[0].shape[0] / img_height
    xmax = box[4] * orig_images[0].shape[1] / img_width
    ymax = box[5] * orig_images[0].shape[0] / img_height
    color = colors[int(box[0])]
    label = '{}: {:.2f}'.format(classes[int(box[0])], box[1])
    current_axis.add_patch(plt.Rectangle((xmin, ymin), xmax-xmin, ymax-ymin, color=color, fill=False, linewidth=2))  
    current_axis.text(xmin, ymin, label, size='x-large', color='white', bbox={'facecolor':color, 'alpha':1.0})
